### PR TITLE
Added v5.12.0 translation, minor edits to better fit strings in Charsheet

### PR DESCRIPTION
**Pull request by Liantefaron**
Identified a problem with the Move, Max. Load and Dodge table: Fits only with Legal paper, not with A4 (seems to be independent of string lengths though).

Also removed v.5.10.x minor versions to reduce clutter.

### CODE REVIEW

**Comment by richardwilkes** [comment]
Looks like you have created some conflicts. Those will need to be resolved before the PR can be merged.

**Comment by Liantefaron** [comment]
OK, I'm away over the long weekend, I'll take a look at this "branches" thingy next week. Would "synchronizing" your master into my master and then - if necessary - re-updating the translations be able to solve this, too?

**Comment by richardwilkes** [comment]
There are multiple ways to deal with this. I was just pointing out that the issue is generally caused by not starting new branches for each set of changes.

**Comment by richardwilkes** [comment]
The last translation file (for v5.15) isn't named correctly.

**Comment by richardwilkes** [comment]
Looks good now, except for the branch conflicts.

**Pull request closed without merging**
