### PR TITLE
Added ru translation for v5.20.4 

### PR DESCRIPTION
**Pull request by NagBoard**
To be refined, there are some original strings missing in original language file for v5.20.4, see issue #4 for more info

### CODE REVIEW

**Comment by richardwilkes** [comment]
Are these the final changes? If so, let me know and I'll merge them.

**Comment by NagBoard** [comment]
I will probably refine everything over the course of couple of days, need time to test it out. Some translations may be a bit rough or formatted not properly.

**Comment by richardwilkes** [comment]
Sounds good. Leave me a message here or on Discord when you're happy with the result and are ready to have it merged.

**Comment by NagBoard** [comment]
Ready to merge I think

**Pull request merged**
